source 'https://bitbucket.org/qranioios/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios , '6.0'

target 'OHAutoNIBi18n' do

	pod 'LRNotificationObserver'
	pod 'ObjcAssociatedObjectHelpers', '~> 1.2.0'

end
